spring.application.name: chap02-mapping-lecture-source
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

  jpa:
    show-sql: true  #jpa 가 대신 만들어주는 SQL 문을 콘솔에 출력할 수 있도록 하는 설정
    database: mysql # 우리가 사용하는 database
    hibernate:
      ddl-auto: create
      # create : 어플리케이션 시작 시 데이터베이스 기존 테이블을 삭제하고 우리가 만든
      #          엔티티 기반으로 테이블을 생성해준다.
      # create-drop : 테이블을 생성하지만, 어플리케이션이 종료되면 다시 삭제를 해준다.
      #               -> test 환경에서 많이 사용함.
      # update : 기존 데이터베이스 스키마를 엔티티 클래스에 맞게끔 업데이트 시킨다.
      #           -> 기존에 데이터의 손실을 유발하지 않고 추가되거나, 삭제되는 것을 반영해준다.
      # none : 데이터베이스의 스키마를 변경하지 않는다. 즉 기존의 데이터베이스를 유지할 수 있다.
    properties:
      hibernate:
        format_sql: true  # sql 문을 들여쓰기 등 쉽게 알아볼 수 있게 format 하는 설정
